name: Deploy Development

on: 
  push:
    branches:
      - dev
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}
  API_URL: ${{ secrets.API_URL_DEV }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            flyctl secrets set TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN && \
            flyctl secrets set API_URL=$API_URL && \
            flyctl deploy \
              -a transport-helper-bot-dev \
              --remote-only 

