name: Deploy Production

on: 
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_PROD }}
  API_URL: ${{ secrets.API_URL_PROD }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            flyctl secrets set TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
            --config ./fly.prod.toml && \
            flyctl secrets set API_URL=$API_URL \
            --config ./fly.prod.toml && \
            flyctl deploy \
              --config ./fly.prod.toml \
              --remote-only \
