name: Deploy Production

on: 
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_PROD }}
  API_URL: ${{ secrets.API_URL_PROD }}
  API_KEY: ${{ secrets.API_KEY }}
  BEDOK_PASSCODE: ${{ secrets.BEDOK_PASSCODE }}


jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: |
            flyctl secrets set TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN API_URL=$API_URL API_KEY=$API_KEY BEDOK_PASSCODE=$BEDOK_PASSCODE \
            --config ./fly.prod.toml --stage && \
            flyctl deploy \
              --config ./fly.prod.toml \
              --remote-only \
